### ISSUE TITLE
能不能把~iphone这段给去掉啊

### ISSUE THREAD

**Issue by jiangyongjian** [yuedong56/Assets.carTool#1]
能不能把~iphone这段给去掉啊

**Comment by yuedong56** [comment]
啥意思？

**Comment by jiangyongjian** [comment]
就是倒出来的图片加上了~iphone

**Comment by yuedong56** [comment]
解压后你拿这个cartool替换掉项目里的cartool就可以了
[cartool.zip](https://github.com/yuedong56/Assets.carTool/files/1592642/cartool.zip)

**Comment by kinddy** [comment]
那怎么还原成assets.car文件呢

**Comment by yuedong56** [comment]
为啥要还原？你本来不就有那个文件吗？如果想把一批图片压缩成assets.car的话，可以用xcode打包
